[theme]

# Primary accent for interactive elements
primaryColor = '#dbc6c6'

# Background color for the main content area
backgroundColor = '#fffbfb'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffeded'

# Color used for almost all text
textColor = '#180f3b'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"